# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: &psql
  adapter: postgresql
  database: school_system
  pool: 5
  username: school_system
  password:
  min_messages: warning

test:
  <<: *psql
  database: school_system_test
  username: school_system

production:
  <<: *psql
  database: school_system_production

